# Generated by Django 3.2.9 on 2023-07-02 12:25

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimestampMixin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('timestampmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='uploads.timestampmixin')),
                ('uuid', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eye Image Uploads',
                'verbose_name_plural': 'Eye Image Uploads',
                'db_table': 'image_uploads',
            },
            bases=('uploads.timestampmixin', models.Model),
        ),
        migrations.CreateModel(
            name='UploadResult',
            fields=[
                ('timestampmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='uploads.timestampmixin')),
                ('image', models.URLField(blank=True)),
                ('image_class', models.CharField(max_length=100)),
                ('results', models.TextField()),
                ('image_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploads.imageupload')),
            ],
            options={
                'verbose_name': 'Image Upload Results',
                'verbose_name_plural': 'Image Upload Results',
                'db_table': 'image_upload_results',
            },
            bases=('uploads.timestampmixin', models.Model),
        ),
    ]
